### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: Design for security
metadata:
  title: Design for security
  description: Design for security
  ms.date: 09/24/2018
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: Check your knowledge
  questions:

  - content: 'Which of the following types of data may need to have security protections?'
    choices:
    - content: 'Customer data that contains personal information'
      isCorrect: false
      explanation: 'It is important to provide proper security protections for this data, but this is not the only correct choice.'
    - content: 'Financial data supporting business operations'
      isCorrect: false
      explanation: 'It is important to provide proper security protections for this data, but this is not the only correct choice.'
    - content: 'Intellectual property'
      isCorrect: false
      explanation: 'It is important to provide proper security protections for this data, but this is not the only correct choice.'
    - content: 'All of the above may need security protections'
      isCorrect: true
      explanation: 'All of the above may merit additional security protections.'

  - content: 'Which of the following is an example of an attack you might see at the policies & access layer?'
    choices:
    - content: 'Exposed credentials posted online'
      isCorrect: true
      explanation: 'Exposed credentials are a huge risk to an organization and apply at the policies & access layer.'
    - content: 'A SYN flood attack'
      isCorrect: false
      explanation: 'SYN flood attacks are a type of denial-of-service attack that are commonly seen on the network perimeter.'
    - content: 'Following an employee into a datacenter without presenting credentials'
      isCorrect: false
      explanation: 'Following an employee into a datacenter is a physical layer attack.'
    - content: 'Ransomware that encrypts the disks of a virtual machine'
      isCorrect: false
      explanation: 'Ransomware attacks are a VM/compute layer attack.'
