### YamlMime:ModuleUnit
uid: learn.azure.store-access-data-cosmos-graph-api.exercise-build-application-that-stores-graph-data-using-gremlin-api
title: Exercise - Build an application that stores graph data using the Gremlin API
metadata:
  title: Exercise - Build an application that stores graph data using the Gremlin API
  description: Build an application that stores graph data using the Gremlin API
  ms.date: 05/03/2019
  author: rmcmurray
  ms.author: robmcm
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  zone_pivot_groups: dev-lang-csharp-javascript
  ROBOTS: NOINDEX
durationInMinutes: 12
azureSandbox: true
interactive: bash
content: |
  [!include[](includes/4-exercise-build-application-that-stores-graph-data-using-gremlin-api.md)]