### YamlMime:ModuleUnit
uid: learn.azure.store-access-data-cosmos-graph-api.query-graph-data-from-an-application-using-gremlin-api
title: Query graph data from an application using gremlin api
metadata:
  title: Query graph data from an application using gremlin api
  description: Query graph data from an application using gremlin api
  ms.date: 05/03/2019
  author: rmcmurray
  ms.author: robmcm
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 2
content: |
  [!include[](includes/5-query-graph-data-from-an-application-using-gremlin-api.md)]