### YamlMime:ModuleUnit
uid: learn.principles-cloud-computing.4-cloud-deployment-models
title: Cloud deployment models
metadata:
  title: Cloud deployment models
  description: Cloud deployment models
  ms.date: 12/20/2018
  author: patridge 
  ms.author: adpatrid
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](includes/4-cloud-deployment-models.md)]