### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: Exercise - Configure applications to send or receive messages through an Event Hub
metadata:
  title: Exercise - Configure applications to send or receive messages through an Event Hub
  description: Configure applications to send or receive messages through an Event Hub
  ms.date: 08/26/2019
  author: cryophobia
  ms.author: chrvaw
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]