### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: Enable and configure Azure VM disk cache with the Azure portal
metadata:
  title: Enable and configure Azure VM disk cache with the Azure portal
  description: Enable and configure Azure VM disk cache with the Azure portal
  ms.date: 09/24/2018
  author: cryophobia
  ms.author: chrvaw
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)