### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: Exercise - Enable and configure Azure VM disk cache with the Azure portal
metadata:
  title: Exercise - Enable and configure Azure VM disk cache with the Azure portal
  description: Exercise - Enable and configure Azure VM disk cache with the Azure portal
  ms.date: 09/24/2018
  author: cryophobia
  ms.author: chrvaw
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
azureSandbox: true
durationInMinutes: 10
content: |
  [!include[](includes/4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)]