### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.5-manage-cache-settings-with-powershell
title: Manage cache settings with PowerShell
metadata:
  title: Manage cache settings with PowerShell
  description: Manage cache settings with PowerShell
  ms.date: 09/24/2018
  author: cryophobia
  ms.author: chrvaw
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/5-manage-cache-settings-with-powershell.md)]