### YamlMime:ModuleUnit
uid: learn.ha-application-storage-with-grs.4-design-applications-ha-dr
metadata:
  title: Design HA applications to handle disaster recovery
  description: In this unit, you learn how to design HA applications to handle disaster recovery.
  ms.date: 09/03/2019
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
title: Design HA applications to handle disaster recovery
durationInMinutes: 8
content: |
  [!include[](includes/4-design-applications-ha-dr.md)]
