### YamlMime:ModuleUnit
uid: learn.ha-application-storage-with-grs.5-exercise-deploy-ha-application
metadata:
  title: Exercise - Deploy a highly available application
  description: In this unit, you learn how to deploy and test a highly available application.
  ms.date: 09/03/2019
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
title: Exercise - Deploy a highly available application
azureSandbox: true
durationInMinutes: 12
content: |
  [!include[](includes/5-exercise-deploy-ha-application.md)]
