### YamlMime:ModuleUnit
uid: learn.end-to-end-encryption-with-app-gateway.3-configure-backend-pools-for-encryption
metadata:
  title: Configure backend pools for encryption
  description: Configure backend pools for encryption
  ms.date: 06/28/2019
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
title: Configure backend pools for encryption
durationInMinutes: 10
content: |
  [!include[](includes/3-configure-backend-pools-for-encryption.md)]