### YamlMime:ModuleUnit
uid: learn.end-to-end-encryption-with-app-gateway.6-exercise-configure-listener-for-encryption
metadata:
  title: Exercise - Configure an Application Gateway listener for encryption
  description: Exercise - Configure an Application Gateway listener for encryption
  ms.date: 06/28/2019
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
title: Exercise - Configure an Application Gateway listener for encryption
durationInMinutes: 10
interactive: bash
azureSandbox: true
content: |
  [!include[](includes/6-exercise-configure-listener-for-encryption.md)]