### YamlMime:ModuleUnit
uid: learn-wwl.app-and-infra-migration-and-modernization.3-application-portfolio-assessment
title: Application portfolio assessment
metadata:
  title: Application portfolio assessment
  description: Application portfolio assessment
  ms.date: 01/31/2019
  author: maargued
  ms.author: maargued
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 11
content: |
  [!include[](includes/3-Application-portfolio-assessment.md)]