### YamlMime:ModuleUnit
uid: learn-wwl.app-and-infra-migration-and-modernization.5-application-modernization
title: Application modernization
metadata:
  title: Application modernization
  description: Application modernization
  ms.date: 01/31/2019
  author: maargued
  ms.author: maargued
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/5-Application-modernization.md)]