### YamlMime:ModuleUnit
uid: learn-wwl.ai-strategy-to-create-business-value.transform-applications-case-study-introduction
title: Transform your applications with AI - Case study introduction
metadata:
  title: Transform your applications with AI - Case study introduction
  description: Telefónica is one of the world’s largest telecommunications companies. Like all telco companies, it has been hit hard by digital disruption and changing customer preferences. It also operates in geographies like Latin America that are particularly vulnerable to sudden market changes. This case study describes how Telefónica used AI to transform its relationship with customers. With AI, they increased customer loyalty and retention by improving their experience while giving them more choice about how they interact with the company and consume its products and services. Along with this case study is a video in which Chema Alonso, Telefónica’s Chief Data Officer, shares his perspective on AI transformation.
  ms.date: 04/26/2019
  author: RWortmanMorris
  ms.author: rawortma
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](includes/3-transform-applications-case-study-introduction.md)] 