### YamlMime:ModuleUnit
uid: learn-wwl.ai-strategy-to-create-business-value.transform-applications-executive-QA
title: Transform your applications with AI - Executive Q&A
metadata:
  title: Transform your applications with AI - Executive Q&A
  description: Learn how one of the largest telecommunication companies in the world is strategically thinking about AI from Chema Alonso, Telefonica's Chief Data Officer. In this video you will hear how they are prioritizing their AI investments, the benefits they are extracting from these investments, and how they will ensure Telefonica will continue to be an AI-led company moving forward.
  ms.date: 04/26/2019
  author: RWortmanMorris
  ms.author: rawortma
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](includes/4-transform-applications-executive-QA.md)] 