### YamlMime:ModuleUnit
uid: learn-wwl.ai-strategy-to-create-business-value.transform-applications-case-study-resolution
title: Transform your applications with AI - Case study resolution
metadata:
  title: Transform your applications with AI - Case study resolution
  description: In this unit, you will learn how Telefónica transformed its organization with AI. You will learn the importance of both modernizing existing applications and enabling your technical development teams with AI. Some new AI services can be easily integrated into legacy systems without the need to create and invest in new models and complex deep learning processes. Additionally, by enabling technical development teams with the building blocks of AI, you can bring AI to every application, driving immediate results and accelerating innovation.
  ms.date: 04/26/2019
  author: RWortmanMorris
  ms.author: rawortma
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10 
content: |
  [!include[](includes/5-transform-applications-case-study-resolution.md)] 