### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: Identify performance bottlenecks in your application
metadata:
  title: Identify performance bottlenecks in your application
  description: In this unit we'll discuss how to identify performance bottlenecks in your application
  ms.date: 09/24/2018
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 9
content: |
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: Check your knowledge
  questions:

  - content: 'Which of the following best describes Application Insights?'
    choices:
    - content: 'A single view for all your monitoring needs in Azure'
      isCorrect: false
      explanation: 'While Application Insights can provide a wealth of data on your application performance, is it not a comprehensive Azure monitoring solution.'
    - content: 'An implementation of the health endpoint monitoring pattern'
      isCorrect: false
      explanation: 'The health endpoint monitoring pattern focuses on monitoring endpoints exposed by your application for overall health.'
    - content: 'A workspace to enable collection of logs across infrastructure and applications'
      isCorrect: false
      explanation: 'Log Analytics is a workspace that enables the collection of logs across infrastructure and applications.'
    - content: 'A service to monitor availability, performance, and usage of web applications'
      isCorrect: true
      explanation: 'Application Insights is a service to monitor availability, performance, and usage of web applications.'

  - content: 'True or false: Log Analytics tracks custom logs and metrics.'
    choices:
    - content: 'True'
      isCorrect: true
      explanation: 'For custom logs and metrics, you can use the HTTP Data Collector API to write data to Log Analytics from any REST API client or an Azure Logic App to write data from a custom workflow.'
    - content: 'False'
      isCorrect: false
      explanation: 'For custom logs and metrics, you can use the HTTP Data Collector API to write data to Log Analytics from any REST API client or an Azure Logic App to write data from a custom workflow.'