### YamlMime:ModuleUnit
uid: learn.azure.stage-deploy-app-service-deployment-slots.4-deploy-a-web-app-by-swapping-deployment-slots
title: Deploy a web app by swapping deployment slots
metadata:
  title: Deploy a web app by swapping deployment slots
  description: Get details on what happens when you swap deployment slots.
  ms.date: 03/27/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 8
content: |
  [!include[](includes/4-deploy-a-web-app-by-swapping-deployment-slots.md)]
