### YamlMime:ModuleUnit
uid: learn.azure.capture-application-logs-app-service.2-enable-and-configure-app-service-application-logging
title: Enable and Configure App Service Application Logging
metadata:
  title: Enable and Configure App Service Application Logging
  description: Enable and Configure App Service Application Logging
  ms.date: 03/20/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](includes/2-enable-and-configure-app-service-application-logging.md)]
quiz:
  title: Check your knowledge
  questions:
  - content: What types of Web apps can save logs to Azure Blob storage?
    choices:
    - content: Node.js apps on Windows.
      isCorrect: true
      explanation: Any app that runs on Windows can save logs to Blob storage.
    - content: Node.js apps on Linux.
      isCorrect: false
      explanation: Linux apps cannot write logs to Blob storage.
    - content: ASP.NET Core apps on Linux.
      isCorrect: false
      explanation: Linux apps cannot write logs to Blob storage.

  - content: Why is file system logging automatically turned off after 12 hours?
    choices:
    - content: To optimize app performance.
      isCorrect: true
      explanation: Excessive logging can potentially cause app performance to degrade.
    - content: So that storage space can be reused.
      isCorrect: false
      explanation: There is no limit on storage space, but excessive logging can consume significant amounts of Azure storage, and add to billing overhead.
    - content: To enable Web apps to reinstantiate on different server instances, with different file system storage.
      isCorrect: false
      explanation: Web apps use a virtual file system, and restarting an app does not lose its association with this storage.