### YamlMime:ModuleUnit
uid: learn.azure.capture-application-logs-app-service.5-view-live-application-logging-activity-with-the-log-streaming-service-using-azure-cli
title: Exercise - View Live Application Logging with the Log Streaming Service using Azure CLI
metadata:
  title: Exercise - View Live Application Logging with the Log Streaming Service using Azure CLI
  description: View Live Application Logging with the Log Streaming Service using Azure CLI
  ms.date: 03/20/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  zone_pivot_groups: dev-lang-csharp-javascript
  ROBOTS: NOINDEX
durationInMinutes: 5
interactive: bash
azureSandbox: true
content: |
  [!include[](includes/5-view-live-application-logging-activity-with-the-log-streaming-service-using-azure-cli.md)]