### YamlMime:ModuleUnit
uid: learn-sqlserver.automatically-tune-sql-server-linux.5-exercise-configure-sql-server-use-query-store-autotuning
title: Configure SQL Server to use Query Store and autotuning
metadata:
  title: Configure SQL Server to use Query Store and autotuning
  description: In this unit, you will set up Query Store and autotuning and then use Azure Data Studio to monitor the effect on performance.
  ms.date: 06/11/2019
  author: alistairmatthews
  ms.author: v-alism
  ms.topic: interactive-tutorial
  ms.prod: learning-sqlserver
  ROBOTS: NOINDEX
durationInMinutes: 5
## TODO: Update this when we have the correct Lab ID
labId: 47218
content: |
  [!include[](includes/5-exercise-configure-sql-server-use-query-store-autotuning.md)]