### YamlMime:ModuleUnit
uid: learn.deep-learning-in-azure-databricks.5-cleanup-the-environment
metadata:
  title: Clean up the environment
  description: Clean up and remove Azure resources used by this lab.
  ms.date: 02/20/2019
  author: barlan
  ms.author: barlan
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: Clean up the environment
durationInMinutes: 2
content: |
  [!include[](includes/5-cleanup-the-environment.md)]
