### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: Create an Azure IoT Central application
metadata:
  title: Create an Azure IoT Central application
  description: Create an Azure IoT Central application
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/1-create-azure-iot-central-application.md)]