### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: Connect your simulated coffee machine to the application
metadata:
  title: Connect your simulated coffee machine to the application
  description: Connect your simulated coffee machine to the application
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
interactive: bash
azureSandbox: true
durationInMinutes: 15
content: |
  [!include[](includes/3-connect-your-application-to-simulator.md)]