### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: Configure rules and actions to monitor your coffee machine
metadata:
  title: Configure rules and actions to monitor your coffee machine
  description: Configure rules and actions to monitor your coffee machine
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 12
content: |
  [!include[](includes/5-configure-rules-and-actions.md)]