### YamlMime:ModuleUnit
uid: learn.understanding-the-sql-dw-connector-with-azure-databricks.2-setup-the-environment
title: Set up the environment
metadata:
  title: Set up the environment
  description: Set up the required services in your Azure subscription.
  ms.date: 02/20/2019
  author: barlan
  ms.author: barlan
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/2-setup-the-environment.md)]