### YamlMime:ModuleUnit
uid: learn.azdo.run-quality-tests-build-pipeline.3-set-up-environment
title: Exercise - Set up your Azure DevOps environment
metadata:
  title: Exercise - Set up your Azure DevOps environment
  description: Run a template to set up your Azure DevOps environment.
  ms.date: 06/21/2019
  author: tpetchel
  ms.author: thpetche
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/3-set-up-environment.md)]