### YamlMime:ModuleUnit
uid: learn.capture-page-load-times-application-insights.2-enable-application-insights
title: Enable Application Insights on an Azure web app
metadata:
  title: Enable Application Insights on an Azure web app
  description: How to enable Application Insights for an existing Azure web app.
  ms.date: 01/08/2019
  author: adrianstevens
  ms.author: adrianstevens
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](includes/2-enable-application-insights.md)]
quiz:
  title: Enable Application Insights on an Azure web app
  questions:
  - content: "You want to make sure that admins know as soon as a web app becomes overloaded. Which feature of Application Insights should you use?"
    choices:
    - content: "Alerts"
      isCorrect: true
      explanation: "You can create an alert that triggers when a condition is satisfied - for example, when the web app is overloaded. When the alert triggers, you can configure it to send an email, for example, to inform admins."
    - content: "Live metrics streams"
      isCorrect: false
      explanation: "Live metrics streams will show whether a web app is overloaded but only when admins are looking at them. To ensure admins know about overloads as soon as the app is overloaded, use an alert."
    - content: "Usage Analysis"
      isCorrect: false
      explanation: "Usage Analysis will show past periods of heavy web app utilization, but only when admins review it. To ensure admins know about overloads as soon as the app is overloaded, use an alert."
  - content: "You have a Linux-based web app that runs in the Azure App Service. You want to display basic performance data in an Application Insights dashboard. Which method should you use to instrument your app?"
    choices:
    - content: "Runtime instrumentation"
      isCorrect: false
      explanation: "Runtime instrumentation is available only for Windows apps because it relies on features of IIS. For Linux-based apps, which run on Apache, you need to use build-time instrumentation."
    - content: "Automatic client-side telemetry"
      isCorrect: false
      explanation: "Automatic client-side telemetry is available only for Windows apps because it relies on features of IIS. For Linux-based apps, which run on Apache, you need to use build-time instrumentation."
    - content: "Build-time instrumentation"
      isCorrect: true
      explanation: "Because your app is based on Linux, you need to use build-time instrumentation. Runtime instrumentation and automatic client-side telemetry are available only for Windows apps."
      