### YamlMime:ModuleUnit
uid: learn.capture-page-load-times-application-insights.3-exercise-enable-application-insights
title: Exercise - Enable Application Insights on an Azure web app
metadata:
  title: Exercise - Enable Application Insights on an Azure web app
  description: How to enable Application Insights for an existing Azure web app.
  ms.date: 01/08/2019
  author: adrianstevens
  ms.author: adrianstevens
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](includes/3-exercise-enable-application-insights.md)]