### YamlMime:ModuleUnit
uid: learn.instrument-web-app-code-with-application-insights.4-instrument-the-application
title: Instrument the application
metadata:
  title: Instrument the application
  description: In this unit, you'll learn why and how to add custom telemetry code to a web application.
  ms.date: 02/27/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 7
content: |
  [!include[](includes/4-instrument-the-application.md)]