### YamlMime:ModuleUnit
uid: learn.instrument-web-app-code-with-application-insights.5-instrument-the-application
title: Exercise - Instrument the application
metadata:
  title: Exercise - Instrument the application
  description: In this unit, you'll write code that calls the Application Insights SDK and stores custom data in Application Insights in Azure.
  ms.date: 02/27/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
azureSandbox: true
interactive: bash
content: |
  [!include[](includes/5-instrument-the-application.md)]