### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Configure Azure Cache for Redis
metadata:
  title: Configure Azure Cache for Redis
  description: Configure Azure Cache for Redis
  ms.date: 09/24/2018
  author: rmcmurray
  ms.author: robmcm
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/3-configure-redis-cache.md)]