### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: Exercise - Set environment variables
  description: Set environment variables in Azure Container Instances.
  ms.date: 07/26/2019
  author: cryophobia
  ms.author: chrvaw
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
title: Exercise - Set environment variables
durationInMinutes: 10
content: |
  [!include[](includes/4-use-environment-variables.md)]