### YamlMime:ModuleUnit
uid: learn.azure.organize-blobs-properties-metadata.view-blob-properties-using-application-code
title: Exercise - View blob properties using application code
metadata:
  title: Exercise - View blob properties using application code
  description: Exercise - View blob properties using application code
  ms.date: 04/26/2019
  author: rmcmurray
  ms.author: robmcm
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
interactive: bash
azureSandbox: true
content: |
  [!include[](includes/4-view-blob-properties-using-application-code.md)]