### YamlMime:ModuleUnit
uid: learn.load-test-web-app-azure-devops.6-use-azure-devops-to-customize-and-reconfigure-web-app-load-tests
title: Exercise - Use Azure DevOps to customize and reconfigure web app load tests
metadata:
  title: Exercise - Use Azure DevOps to customize and reconfigure Web app load tests
  description: Use the Azure DevOps environment to compare results from two tests runs and to test with multiple URLs, with URL query strings, and with HAR files to see how an app performs against a typical user session.
  ms.date: 01/08/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 15
content: |
  [!include[](includes/6-use-azure-devops-to-customize-and-reconfigure-web-app-load-tests.md)]