### YamlMime:ModuleUnit
uid: learn.prepare-azure-dev-environment.3-exercise-set-up-dev-environment
title: Exercise - Set up your development environment
metadata:
  title: Exercise - Set up your development environment
  description: Exercise - Set up your development environment
  ms.date: 07/01/2019
  author: patridge
  ms.author: adpatrid
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  zone_pivot_groups: ide
durationInMinutes: 15
content: |
  [!include[](includes/3-exercise-set-up-dev-environment.md)]