### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Network security
metadata:
  title: Network security
  description: In this unit we'll discuss how to secure your network infrastructure
  ms.date: 09/24/2018
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](includes/6-network-security.md)]
quiz:
  title: Check your knowledge
  questions:
  - content: 'Azure network security groups can be used to secure communication between which of the following?'
    choices:
    - content: 'Communication between Azure virtual machines and the internet'
      isCorrect: false
      explanation: 'Network security groups can be used to secure this communication flow, but this is not the only correct choice.'
    - content: 'Communication between Azure virtual machines within a VNet'
      isCorrect: false
      explanation: 'Network security groups can be used to secure this communication flow, but this is not the only correct choice.'
    - content: 'Communication between Azure virtual machines and systems in an on-premises network'
      isCorrect: false
      explanation: 'Network security groups can be used to secure this communication flow, but this is not the only correct choice.'
    - content: 'All of the above'
      isCorrect: true
      explanation: 'Network security groups are fully customizable, and give you the ability to fully lock down network communication to and from your virtual machines.'

  - content: 'Which of the following is not a method for protecting internet facing services from network attacks?'
    choices:
    - content: 'Azure DDoS'
      isCorrect: false
      explanation: 'Azure DDoS can be used to protect your internet facing services from a DoS attack. '
    - content: 'Azure Application Gateway WAF'
      isCorrect: false
      explanation: 'Application Gateway WAF can be used to protect your internet facing services from attacks such as XSS and SQL injection.'
    - content: 'Azure Disk Encryption'
      isCorrect: true
      explanation: 'Azure Disk Encryption protects your virtual machine VHDs from exposure, but does not provide protection from network based attacks.'
    - content: 'A network virtual appliance'
      isCorrect: false
      explanation: 'Network virtual appliances can provide customized network protection for your internet facing resources.'