### YamlMime:ModuleUnit
uid: learn.design-your-migration-to-azure.3-assess-your-environment
metadata:
  title: Assess your environment with Azure Migrate
  description: An overview of Azure Migrate, a service that assesses readiness and assists you with the migration to Azure from an on-premises environment.
  ms.date: 07/30/2019
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
title: Assess your environment with Azure Migrate
durationInMinutes: 10
content: |
  [!include[](includes/3-assess-your-environment.md)]
quiz:
  title: Check your knowledge
  questions:
  - content: "Which of the following are valid reasons to use Azure Migrate?"
    choices:
    - content: "Assess Azure readiness, obtain VM size recommendations, migrate with confidence"
      isCorrect: true
      explanation: "All three are valid reasons to use Azure Migrate."
    - content: "Assess Azure readiness, migrate with confidence, migrate databases"
      isCorrect: false
      explanation: "Migrate databases isn't a feature of Azure Migrate. You use Azure Database Migration Service for database migration."
    - content: "Obtain VM size recommendations, assess Azure readiness, assess physical servers"
      isCorrect: false
      explanation: "Azure Migrate can't be used to assess physical servers. Third-party partner tools are required to do that."
  - content: "What is the order of steps to complete an Azure readiness assessment?"
    choices:
    - content: "Install the Dependency Agent on each on-premises VM, install the collector appliance on the vCenter Server, edit the default properties of an assessment, and then create the assessment."
      isCorrect: false
      explanation: "Download and install the collector appliance first, and then install the dependency agents. You can't change the properties of an assessment until one has been created."
    - content: "Install dependency agents on each on-premises VM, install the collector appliance on the vCenter Server, create the assessment, and then edit the default properties of the assessment to your requirements."
      isCorrect: false
      explanation: "Download and install the collector appliance first, and then install the dependency agents."
    - content: "Install the collector appliance on the vCenter Server, install dependency agents on each on-premises VM, create the assessment, and then edit the default properties of the assessment to your requirements."
      isCorrect: true
      explanation: "This is the correct answer. Remember that installing the dependency agents is optional. Also, you don't need to edit the assessment properties if the defaults are sufficient."
