### YamlMime:ModuleUnit
uid: learn-sqlserver.test-optimize-sql-server-databases-using-dea.4-configure-new-capture
title: Configure a new capture
metadata:
  title: Configure a new capture
  description: Configure a new capture
  ms.date: 01/31/2019
  author: geoffallix
  ms.author: v-gea
  ms.topic: interactive-tutorial
  ms.prod: learning-sqlserver
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/4-configure-new-capture.md)]