### YamlMime:ModuleUnit
uid: learn.persist-data-ef-core.2-setup-environment
metadata:
  title: Set up the environment
  description: Provision Azure resources, download the ASP.NET Core starter project, and tour the starter project.
  ms.date: 04/20/2019
  author: scottaddie
  ms.author: scaddie
  ms.topic: interactive-tutorial
  ms.prod: learning-aspnetcore
  ROBOTS: NOINDEX
title: Set up the environment
azureSandbox: true
interactive: bash
durationInMinutes: 10
content: |
  [!include[](includes/2-setup-environment.md)]