### YamlMime:ModuleUnit
uid: learn.persist-data-ef-core.3-configure-db-connection
metadata:
  title: Exercise - Configure the database connection
  description: Learn how to configure a database connection in an ASP.NET Core app.
  ms.date: 04/20/2019
  author: scottaddie
  ms.author: scaddie
  ms.topic: interactive-tutorial
  ms.prod: learning-aspnetcore
  ROBOTS: NOINDEX
title: Exercise - Configure the database connection
azureSandbox: true
interactive: bash-editor
durationInMinutes: 8
content: |
  [!include[](includes/3-configure-db-connection.md)]