### YamlMime:ModuleUnit
uid: learn.secure-your-azure-sql-database.4-data-security
metadata:
  title: Exercise - Secure your data in transit, at rest, and on display
  description: Data security
  ms.date: 11/09/2018
  author: rmcmurray
  ms.author: robmcm
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
interactive: bash
azureSandbox: true
title: Exercise - Secure your data in transit, at rest, and on display
durationInMinutes: 8
content: |
  [!include[](includes/4-data-security.md)]