### YamlMime:ModuleUnit
uid: learn.azure.improve-api-performance-with-apim-caching-policy.4-configure-a-caching-policy
title: Configure a caching policy
metadata:
  title: Configure a caching policy
  description: In this unit, you will learn how to use the cache control policies in API Management to accelerate responses.
  ms.date: 04/25/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/4-configure-a-caching-policy.md)]