### YamlMime:ModuleUnit
uid: learn.azure.improve-api-performance-with-apim-caching-policy.5-exercise-configure-a-caching-policy
title: Exercise - Configure a caching policy
metadata:
  title: Exercise - Configure a caching policy
  description: In this unit, you will create a new instance of API Management and use it to set up an API cache.
  ms.date: 04/25/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 25
azureSandbox: true
interactive: bash
content: |
  [!include[](includes/5-exercise-configure-a-caching-policy.md)]