### YamlMime:ModuleUnit
uid: learn.performing-text-analytics-with-azure-databricks.5-cleanup-the-environment
metadata:
  title: Cleanup the environment
  description: Cleanup and terminate Azure resources used by this lab.
  ms.date: 02/20/2019
  author: barlan
  ms.author: barlan
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: Cleanup the environment
durationInMinutes: 2
content: |
  [!include[](includes/5-cleanup-the-environment.md)]
