### YamlMime:ModuleUnit
uid: learn.azure.improve-developer-experience-of-an-api-with-swagger-documentation.publish-openapi-documentation
title: Document an ASP.Net Core Web API with Swagger tools
metadata:
  title: Document an ASP.Net Core Web API with Swagger tools
  description: Document an ASP.Net Core Web API with Swagger tools
  ms.date: 05/06/2019
  author: andrewjbyrne
  ms.author: anbyrne
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/2-publish-openapi-documentation.md)]