### YamlMime:ModuleUnit
uid: learn.azure.improve-developer-experience-of-an-api-with-swagger-documentation.exercise-enable-swagger-and-swashbuckle
title: Exercise - Enable Swagger documentation in an ASP.NET Core Web API app
metadata:
  title: Exercise - Enable Swagger documentation in an ASP.NET Core Web API app
  description: Practice enabling Swagger and Swashbuckle in an ASP.NET Core Web API app
  ms.date: 05/06/2019
  author: andrewjbyrne
  ms.author: anbyrne
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
interactive: bash
azureSandbox: true
durationInMinutes: 8
content: |
  [!include[](includes/3-exercise-enable-swagger-and-swashbuckle.md)]